language: java
before_install: cd "JMapper Framework"
install: mvn install -DskipTests=false -Dgpg.skip=true

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  
after_success:
  - mvn clean -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID cobertura:cobertura coveralls:report
  
